/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as UnauthenticatedImport } from './routes/unauthenticated'
import { Route as OidcCallbackImport } from './routes/oidc-callback'
import { Route as LogoutImport } from './routes/logout'
import { Route as ErrorImport } from './routes/error'
import { Route as AccessDeniedImport } from './routes/access-denied'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as IndexImport } from './routes/index'
import { Route as AuthenticatedIndexImport } from './routes/_authenticated/index'
import { Route as AuthenticatedApplicationUrlsImport } from './routes/_authenticated/application-urls'
import { Route as AuthenticatedRequestAccessIndexImport } from './routes/_authenticated/request-access/index'
import { Route as AuthenticatedLaunchpadIndexImport } from './routes/_authenticated/launchpad/index'
import { Route as AuthenticatedRequestAccessAuthIndexImport } from './routes/_authenticated/request-access/auth/index'
import { Route as AuthenticatedRequestAccessAuthUsersUsernameImport } from './routes/_authenticated/request-access/auth/users/$username'

// Create/Update Routes

const UnauthenticatedRoute = UnauthenticatedImport.update({
  path: '/unauthenticated',
  getParentRoute: () => rootRoute,
} as any)

const OidcCallbackRoute = OidcCallbackImport.update({
  path: '/oidc-callback',
  getParentRoute: () => rootRoute,
} as any)

const LogoutRoute = LogoutImport.update({
  path: '/logout',
  getParentRoute: () => rootRoute,
} as any)

const ErrorRoute = ErrorImport.update({
  path: '/error',
  getParentRoute: () => rootRoute,
} as any)

const AccessDeniedRoute = AccessDeniedImport.update({
  path: '/access-denied',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedIndexRoute = AuthenticatedIndexImport.update({
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedApplicationUrlsRoute =
  AuthenticatedApplicationUrlsImport.update({
    path: '/application-urls',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedRequestAccessIndexRoute =
  AuthenticatedRequestAccessIndexImport.update({
    path: '/request-access/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedLaunchpadIndexRoute =
  AuthenticatedLaunchpadIndexImport.update({
    path: '/launchpad/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedRequestAccessAuthIndexRoute =
  AuthenticatedRequestAccessAuthIndexImport.update({
    path: '/request-access/auth/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedRequestAccessAuthUsersUsernameRoute =
  AuthenticatedRequestAccessAuthUsersUsernameImport.update({
    path: '/request-access/auth/users/$username',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/access-denied': {
      id: '/access-denied'
      path: '/access-denied'
      fullPath: '/access-denied'
      preLoaderRoute: typeof AccessDeniedImport
      parentRoute: typeof rootRoute
    }
    '/error': {
      id: '/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof ErrorImport
      parentRoute: typeof rootRoute
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutImport
      parentRoute: typeof rootRoute
    }
    '/oidc-callback': {
      id: '/oidc-callback'
      path: '/oidc-callback'
      fullPath: '/oidc-callback'
      preLoaderRoute: typeof OidcCallbackImport
      parentRoute: typeof rootRoute
    }
    '/unauthenticated': {
      id: '/unauthenticated'
      path: '/unauthenticated'
      fullPath: '/unauthenticated'
      preLoaderRoute: typeof UnauthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/application-urls': {
      id: '/_authenticated/application-urls'
      path: '/application-urls'
      fullPath: '/application-urls'
      preLoaderRoute: typeof AuthenticatedApplicationUrlsImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/launchpad/': {
      id: '/_authenticated/launchpad/'
      path: '/launchpad'
      fullPath: '/launchpad'
      preLoaderRoute: typeof AuthenticatedLaunchpadIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/request-access/': {
      id: '/_authenticated/request-access/'
      path: '/request-access'
      fullPath: '/request-access'
      preLoaderRoute: typeof AuthenticatedRequestAccessIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/request-access/auth/': {
      id: '/_authenticated/request-access/auth/'
      path: '/request-access/auth'
      fullPath: '/request-access/auth'
      preLoaderRoute: typeof AuthenticatedRequestAccessAuthIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/request-access/auth/users/$username': {
      id: '/_authenticated/request-access/auth/users/$username'
      path: '/request-access/auth/users/$username'
      fullPath: '/request-access/auth/users/$username'
      preLoaderRoute: typeof AuthenticatedRequestAccessAuthUsersUsernameImport
      parentRoute: typeof AuthenticatedImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  AuthenticatedRoute: AuthenticatedRoute.addChildren({
    AuthenticatedApplicationUrlsRoute,
    AuthenticatedIndexRoute,
    AuthenticatedLaunchpadIndexRoute,
    AuthenticatedRequestAccessIndexRoute,
    AuthenticatedRequestAccessAuthIndexRoute,
    AuthenticatedRequestAccessAuthUsersUsernameRoute,
  }),
  AccessDeniedRoute,
  ErrorRoute,
  LogoutRoute,
  OidcCallbackRoute,
  UnauthenticatedRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_authenticated",
        "/access-denied",
        "/error",
        "/logout",
        "/oidc-callback",
        "/unauthenticated"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_authenticated": {
      "filePath": "_authenticated.tsx",
      "children": [
        "/_authenticated/application-urls",
        "/_authenticated/",
        "/_authenticated/launchpad/",
        "/_authenticated/request-access/",
        "/_authenticated/request-access/auth/",
        "/_authenticated/request-access/auth/users/$username"
      ]
    },
    "/access-denied": {
      "filePath": "access-denied.tsx"
    },
    "/error": {
      "filePath": "error.tsx"
    },
    "/logout": {
      "filePath": "logout.tsx"
    },
    "/oidc-callback": {
      "filePath": "oidc-callback.tsx"
    },
    "/unauthenticated": {
      "filePath": "unauthenticated.tsx"
    },
    "/_authenticated/application-urls": {
      "filePath": "_authenticated/application-urls.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/": {
      "filePath": "_authenticated/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/launchpad/": {
      "filePath": "_authenticated/launchpad/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/request-access/": {
      "filePath": "_authenticated/request-access/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/request-access/auth/": {
      "filePath": "_authenticated/request-access/auth/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/request-access/auth/users/$username": {
      "filePath": "_authenticated/request-access/auth/users/$username.tsx",
      "parent": "/_authenticated"
    }
  }
}
ROUTE_MANIFEST_END */
