apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    name: {{ .Chart.Name }}
  name: {{ .Chart.Name }}
data:
  JWT_OIDC_ALGORITHMS: {{ .Values.auth.jwt.alg }}
  JWT_OIDC_AUDIENCE: {{ .Values.auth.jwt.aud }}
  JWT_OIDC_CACHING_ENABLED: "{{ .Values.auth.jwt.cacheEnabled }}"
  JWT_OIDC_ISSUER: {{ .Values.auth.jwt.issuer }}
  JWT_OIDC_JWKS_CACHE_TIMEOUT: "{{ .Values.auth.jwt.cacheTimeout }}"
  JWT_OIDC_WELL_KNOWN_CONFIG: {{ .Values.auth.jwt.wellKnownConfig }}
  PYTHONBUFFERED: "{{ .Values.python.pythonBuffered }}"
  KEYCLOAK_BASE_URL: {{ .Values.auth.keycloak.uri }}
  KEYCLOAK_REALM_NAME: {{ .Values.auth.keycloak.realm }}
  CONNECT_TIMEOUT: "{{ .Values.python.connectTimeout }}"
  CORS_ORIGIN: "{{ .Values.cors.origin }}"
  APP_NAME: "{{ .Values.app.name }}"
  INTRANET_LAUNCH_URL: "{{ .Values.urls.intranetLaunch }}"
  EPIC_CENTRE_WEB_URL: "{{ .Values.urls.epicCentreWeb }}"
  EPIC_PUBLIC_USER_MANAGEMENT_URL: "{{ .Values.urls.epicPublicUserManagement }}"
  EPIC_ENGAGE_USER_MANAGEMENT_URL: "{{ .Values.urls.epicEngageUserManagement }}"
  EPIC_TRACK_USER_MANAGEMENT_URL: "{{ .Values.urls.epicTrackUserManagement }}"
  EPIC_COMPLIANCE_USER_MANAGEMENT_URL: "{{ .Values.urls.epicComplianceUserManagement }}"
  EPIC_ENGAGE_LAUNCH_URL: "{{ .Values.urls.epicEngageLaunch }}"
  EPIC_SUBMIT_LAUNCH_URL: "{{ .Values.urls.epicSubmitLaunch }}"
  EPIC_PUBLIC_LAUNCH_URL: "{{ .Values.urls.epicPublicLaunch }}"
  EPIC_TRACK_LAUNCH_URL: "{{ .Values.urls.epicTrackLaunch }}"
  EPIC_COMPLIANCE_LAUNCH_URL: "{{ .Values.urls.epicComplianceLaunch }}"
  CONDITION_REPOSITORY_LAUNCH_URL: "{{ .Values.urls.conditionRepositoryLaunch }}"
  EPIC_SUBMIT_USER_MANAGEMENT_URL: "{{ .Values.urls.epicSubmitUserManagement }}"
  DST_EMAIL: "{{ .Values.email.dstEmail }}"
  AUTH_API: "{{ .Values.apis.authApi }}"
  SUBMIT_API_URL: "{{ .Values.apis.submitApi }}"
