apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    name: {{ .Chart.Name }}
  name: {{ .Chart.Name }}
data:
  JWT_OIDC_ALGORITHMS: {{ .Values.auth.jwt.alg }}
  JWT_OIDC_AUDIENCE: {{ .Values.auth.jwt.aud }}
  JWT_OIDC_CACHING_ENABLED: "{{ .Values.auth.jwt.cacheEnabled }}"
  JWT_OIDC_ISSUER: {{ .Values.auth.jwt.issuer }}
  JWT_OIDC_JWKS_CACHE_TIMEOUT: "{{ .Values.auth.jwt.cacheTimeout }}"
  JWT_OIDC_WELL_KNOWN_CONFIG: {{ .Values.auth.jwt.wellKnownConfig }}
  PYTHONBUFFERED: "{{ .Values.python.pythonBuffered }}"
  KEYCLOAK_BASE_URL: {{ .Values.auth.keycloak.uri }}
  KEYCLOAK_REALM_NAME: {{ .Values.auth.keycloak.realm }}
  CONNECT_TIMEOUT: "{{ .Values.python.connectTimeout }}"
  CORS_ORIGIN: "{{ .Values.cors.origin }}"
  APP_NAME: "{{ .Values.app.name }}"
  INTRANET_LAUNCH_URL: "{{ .Values.urls.intranetLaunch }}"
  EPIC_CENTRE_WEB_URL: "{{ .Values.urls.epicCentreWeb }}"
  EPIC_PUBLIC_USER_MANAGEMENT_URL: "{{ .Values.urls.epicPublicUserManagement }}"
  EPIC_ENGAGE_USER_MANAGEMENT_URL: "{{ .Values.urls.epicEngageUserManagement }}"
  EPIC_TRACK_USER_MANAGEMENT_URL: "{{ .Values.urls.epicTrackUserManagement }}"
  EPIC_COMPLIANCE_USER_MANAGEMENT_URL: "{{ .Values.urls.epicComplianceUserManagement }}"
  EPIC_ENGAGE_LAUNCH_URL: "{{ .Values.urls.epicEngageLaunch }}"
  EPIC_SUBMIT_LAUNCH_URL: "{{ .Values.urls.epicSubmitLaunch }}"
  EPIC_PUBLIC_LAUNCH_URL: "{{ .Values.urls.epicPublicLaunch }}"
  EPIC_TRACK_LAUNCH_URL: "{{ .Values.urls.epicTrackLaunch }}"
  EPIC_COMPLIANCE_LAUNCH_URL: "{{ .Values.urls.epicComplianceLaunch }}"
  CONDITION_REPOSITORY_LAUNCH_URL: "{{ .Values.urls.conditionRepositoryLaunch }}"
  EPIC_SUBMIT_USER_MANAGEMENT_URL: "{{ .Values.urls.epicSubmitUserManagement }}"
  DST_EMAIL: "{{ .Values.email.dstEmail }}"
  AUTH_API: "{{ .Values.apis.authApi }}"
  SUBMIT_API_URL: "{{ .Values.apis.submitApi }}"
  EPIC_GROUP_COMPLIANCE: "{{ .Values.epicGroups.compliance }}"
  EPIC_GROUP_CONDITION_REPO: "{{ .Values.epicGroups.conditionRepo }}"
  EPIC_GROUP_SUBMIT: "{{ .Values.epicGroups.submit }}"
  EPIC_GROUP_TRACK: "{{ .Values.epicGroups.track }}"
  EPIC_GROUP_ENGAGE: "{{ .Values.epicGroups.engage }}"
  EPIC_GROUP_CENTRE: "{{ .Values.epicGroups.centre }}"
  EPIC_GROUP_PUBLIC: "{{ .Values.epicGroups.public }}"
  EPIC_ADMIN_SUBGROUP_ADMIN: "{{ .Values.epicAdminSubgroups.admin }}"
  EPIC_ADMIN_SUBGROUP_EAO_MANAGER: "{{ .Values.epicAdminSubgroups.eaoManager }}"
  EPIC_ADMIN_SUBGROUP_INSTANCE_ADMIN: "{{ .Values.epicAdminSubgroups.instanceAdmin }}"
  EPIC_ADMIN_SUBGROUP_SUPERUSER: "{{ .Values.epicAdminSubgroups.superuser }}"
  EPIC_ADMIN_SUBGROUP_SUPER_USER: "{{ .Values.epicAdminSubgroups.superUser }}"
  EPIC_ADMIN_GROUP_PATH_COMPLIANCE: "{{ .Values.epicAdminGroupPaths.compliance }}"
  EPIC_ADMIN_GROUP_PATH_CONDITION_REPO: "{{ .Values.epicAdminGroupPaths.conditionRepo }}"
  EPIC_ADMIN_GROUP_PATH_SUBMIT: "{{ .Values.epicAdminGroupPaths.submit }}"
  EPIC_ADMIN_GROUP_PATH_TRACK: "{{ .Values.epicAdminGroupPaths.track }}"
  EPIC_ADMIN_GROUP_PATH_ENGAGE: "{{ .Values.epicAdminGroupPaths.engage }}"
  EPIC_ADMIN_GROUP_PATH_CENTRE: "{{ .Values.epicAdminGroupPaths.centre }}"
  EPIC_ADMIN_GROUP_PATH_PUBLIC: "{{ .Values.epicAdminGroupPaths.public }}"
  EPIC_APP_CLIENT_CONDITION_REPOSITORY: "{{ .Values.epicAppClients.conditionRepository }}"
  EPIC_APP_CLIENT_EPIC_COMPLIANCE: "{{ .Values.epicAppClients.epicCompliance }}"
  EPIC_APP_CLIENT_EPIC_TRACK: "{{ .Values.epicAppClients.epicTrack }}"
  EPIC_APP_CLIENT_EPIC_PUBLIC: "{{ .Values.epicAppClients.epicPublic }}"
  EPIC_APP_CLIENT_EPIC_SUBMIT: "{{ .Values.epicAppClients.epicSubmit }}"
  EPIC_APP_CLIENT_EPIC_ENGAGE: "{{ .Values.epicAppClients.epicEngage }}"
  EPIC_APP_CLIENT_EPIC_CENTRE: "{{ .Values.epicAppClients.epicCentre }}"
