replicaCount: 1

image:
  repository: image-registry.openshift-image-registry.svc:5000/c72cba-tools/centre-api
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "dev"

resources:
  cpu:
    limit: 100m
    request: 75m
  memory:
    limit: 384Mi
    request: 256Mi

database:
  secret: centre-patroni
  service:
    name: centre-patroni
    port: 5432

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

auth:
  jwt:
    alg: RS256
    aud: epic-centre
    cacheEnabled: true
    issuer: https://dev.loginproxy.gov.bc.ca/auth/realms/eao-epic
    cacheTimeout: "300"
    wellKnownConfig: https://dev.loginproxy.gov.bc.ca/auth/realms/eao-epic/.well-known/openid-configuration
  keycloak:
    uri: https://dev.loginproxy.gov.bc.ca
    realm: eao-epic
    adminClientId:
    adminClientSecret:
python:
  pythonBuffered: 1
  connectTimeout: 60
cors:
  origin: "https://dev.centre.eao.gov.bc.ca,"
