replicaCount: 1

image:
  repository: image-registry.openshift-image-registry.svc:5000/c72cba-tools/centre-api
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "dev"

resources:
  cpu:
    limit: 100m
    request: 75m
  memory:
    limit: 384Mi
    request: 256Mi

database:
  secret: centre-patroni
  service:
    name: centre-patroni
    port: 5432

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

auth:
  jwt:
    alg: RS256
    aud: epic-centre
    cacheEnabled: true
    issuer: https://dev.loginproxy.gov.bc.ca/auth/realms/eao-epic
    cacheTimeout: "300"
    wellKnownConfig: https://dev.loginproxy.gov.bc.ca/auth/realms/eao-epic/.well-known/openid-configuration
  keycloak:
    uri: https://dev.loginproxy.gov.bc.ca
    realm: eao-epic
    adminClientId:
    adminClientSecret:
python:
  pythonBuffered: 1
  connectTimeout: 60
cors:
  origin: "https://system.eao.gov.bc.ca,"

app:
  name: "EPIC Centre"

urls:
  intranetLaunch: https://intranet.gov.bc.ca/eao
  epicCentreWeb: https://system.eao.gov.bc.ca/centre
  epicPublicUserManagement: https://eagle-prod.apps.silver.devops.gov.bc.ca/admin/
  epicEngageUserManagement: https://engage.eao.gov.bc.ca/usermanagement
  epicTrackUserManagement: https://system.eao.gov.bc.ca/admin/users
  epicComplianceUserManagement: https://system.eao.gov.bc.ca/compliance/admin/staff
  epicEngageLaunch: https://engage.eao.gov.bc.ca/
  epicSubmitLaunch: https://dev.submit.eao.gov.bc.ca/
  epicPublicLaunch: https://projects.eao.gov.bc.ca/
  epicTrackLaunch: https://system.eao.gov.bc.ca
  epicComplianceLaunch: https://system.eao.gov.bc.ca/compliance
  conditionRepositoryLaunch: https://system.eao.gov.bc.ca/condition

email:
  dstEmail: 

apis:
  authApi: