"""empty message

Revision ID: 15eafacef9cd
Revises: 85107267fdd3
Create Date: 2025-08-27 14:56:34.089956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15eafacef9cd'
down_revision = '85107267fdd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_applications', schema=None) as batch_op:
        batch_op.drop_constraint('user_applications_user_auth_guid_key', type_='unique')
        batch_op.create_unique_constraint('uq_user_auth_guid_app_id', ['user_auth_guid', 'app_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_applications', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_auth_guid_app_id', type_='unique')
        batch_op.create_unique_constraint('user_applications_user_auth_guid_key', ['user_auth_guid'])

    # ### end Alembic commands ###
