"""Add status column to access_requests table

Revision ID: 1d73d2298efe
Revises: e2f33ae4b62a
Create Date: 2025-09-19 11:28:13.099069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d73d2298efe'
down_revision = 'e2f33ae4b62a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    accessrequestsstatusenum = sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED',
                                       name='accessrequestsstatusenum')
    accessrequestsstatusenum.create(op.get_bind())  # Create the enum type in the database

    with op.batch_alter_table('access_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', accessrequestsstatusenum, nullable=False,
                                      server_default='PENDING'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('access_requests', schema=None) as batch_op:
        batch_op.drop_column('status')
    accessrequestsstatusenum = sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED',
                                       name='accessrequestsstatusenum')
    accessrequestsstatusenum.drop(op.get_bind())  # Drop the enum type from the database

    # ### end Alembic commands ###
