""" Make bookmarks a JSON field in user_applications

Revision ID: 85107267fdd3
Revises: 207e2f39280b
Create Date: 2025-08-26 16:42:11.395085

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '85107267fdd3'
down_revision = '207e2f39280b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bookmarks')
    with op.batch_alter_table('user_applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bookmarks', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_applications', schema=None) as batch_op:
        batch_op.drop_column('bookmarks')

    op.create_table('bookmarks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_app_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('label', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_app_id'], ['user_applications.id'], name='bookmarks_user_app_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='bookmarks_pkey')
    )
    # ### end Alembic commands ###
