"""add ticket_reference to application_urls

Revision ID: 9b0924302709
Revises: a3b0624d1074
Create Date: 2026-02-08 14:31:44.069885

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9b0924302709'
down_revision = 'a3b0624d1074'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application_urls', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ticket_reference', sa.String(length=50), nullable=True))
        batch_op.alter_column('created_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application_urls', schema=None) as batch_op:
        batch_op.alter_column('created_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.drop_column('ticket_reference')

    # ### end Alembic commands ###
