"""add new application to applications table

Revision ID: a1b2c3d4e5f6
Revises: 0ace214f26a2
Create Date: 2025-01-XX XX:XX:XX.XXXXXX

"""
import sqlalchemy as sa
from alembic import op
from datetime import datetime


# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f6'
down_revision = '0ace214f26a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Insert new application into applications table
    applications_table = sa.table(
        'applications',
        sa.column('title', sa.String),
        sa.column('name', sa.String),
        sa.column('description', sa.Text),
        sa.column('launch_url', sa.Text),
        sa.column('is_active', sa.Boolean),
        sa.column('created_date', sa.DateTime),
        sa.column('created_by', sa.String),
    )
    
    op.bulk_insert(
        applications_table,
        [
            {
                'title': 'Intranet',
                'name': 'intranet',
                'description': 'Access the EAO intranet',
                'launch_url': '',
                'created_date': datetime.utcnow(),
                'is_active': True,
            }
        ]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove the application that was added in upgrade()
    op.execute(
        "DELETE FROM applications WHERE name = 'intranet'"
    )
    # ### end Alembic commands ###

