"""add login_history table

Revision ID: b2c3d4e5f6a7
Revises: a1b2c3d4e5f6
Create Date: 2024-12-20 12:00:00.000000

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = 'b2c3d4e5f6a7'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_history',
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_auth_guid', sa.String(), nullable=False),
    sa.Column('last_login_time', sa.DateTime(), nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['applications.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_auth_guid', name='uq_user_auth_guid')
    )
    op.create_index('ix_login_history_app_id', 'login_history', ['app_id'], unique=False)
    op.create_index('ix_login_history_last_login_time', 'login_history', ['last_login_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_login_history_last_login_time', table_name='login_history')
    op.drop_index('ix_login_history_app_id', table_name='login_history')
    op.drop_table('login_history')
    # ### end Alembic commands ###

