"""add renewal status and comments

Revision ID: cde4c372a8f6
Revises: 9b0924302709
Create Date: 2026-02-08 14:43:41.890827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cde4c372a8f6'
down_revision = '9b0924302709'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application_urls', schema=None) as batch_op:
        batch_op.add_column(sa.Column('renewal_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('renewal_comments', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application_urls', schema=None) as batch_op:
        batch_op.drop_column('renewal_comments')
        batch_op.drop_column('renewal_status')

    # ### end Alembic commands ###
