"""add application_urls table

Revision ID: e55517dc0fd8
Revises: b2c3d4e5f6a7
Create Date: 2026-02-07 13:24:08.619392

"""
from datetime import datetime
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e55517dc0fd8'
down_revision = 'c3d4e5f6a7b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_urls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_name', sa.String(length=100), nullable=False),
    sa.Column('environment', sa.String(length=50), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('ssl_expiry', sa.DateTime(), nullable=True),
    sa.Column('ssl_status', sa.String(length=50), nullable=True),
    sa.Column('ssl_error_message', sa.String(length=500), nullable=True),
    sa.Column('ticket_reference', sa.String(length=50), nullable=True),
    sa.Column('renewal_status', sa.String(length=50), nullable=True),
    sa.Column('renewal_comments', sa.Text(), nullable=True),
    sa.Column('last_checked', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
    
    # Seed initial data
    op.bulk_insert(
        sa.table('application_urls',
            sa.Column('app_name', sa.String(length=100)),
            sa.Column('environment', sa.String(length=50)),
            sa.Column('url', sa.String(length=500)),
            sa.Column('created_date', sa.DateTime()),
            sa.Column('created_by', sa.String(length=50)),
            sa.Column('is_active', sa.Boolean())
        ),
        [
            # CENTRE
            {'app_name': 'EPIC Centre', 'environment': 'DEV', 'url': 'https://eao-dev.apps.gold.devops.gov.bc.ca', 'created_date': datetime.utcnow(), 'created_by': 'system', 'is_active': True},
            {'app_name': 'EPIC Centre', 'environment': 'TEST', 'url': 'https://eao-test.apps.gold.devops.gov.bc.ca', 'created_date': datetime.utcnow(), 'created_by': 'system', 'is_active': True},
            {'app_name': 'EPIC Centre', 'environment': 'PROD', 'url': 'https://system.eao.gov.bc.ca/', 'created_date': datetime.utcnow(), 'created_by': 'system', 'is_active': True},
            
            # SUBMIT
            {'app_name': 'EPIC Submit', 'environment': 'DEV', 'url': 'https://dev.submit.eao.gov.bc.ca', 'created_date': datetime.utcnow(), 'created_by': 'system', 'is_active': True},
            {'app_name': 'EPIC Submit', 'environment': 'TEST', 'url': 'https://test.submit.eao.gov.bc.ca', 'created_date': datetime.utcnow(), 'created_by': 'system', 'is_active': True},
            {'app_name': 'EPIC Submit', 'environment': 'PROD', 'url': 'https://submit.eao.gov.bc.ca', 'created_date': datetime.utcnow(), 'created_by': 'system', 'is_active': True},

            # TRACK
            {'app_name': 'EPIC Track', 'environment': 'DEV', 'url': 'https://eao-dev.apps.gold.devops.gov.bc.ca/track', 'created_date': datetime.utcnow(), 'created_by': 'system', 'is_active': True},
            {'app_name': 'EPIC Track', 'environment': 'TEST', 'url': 'https://eao-test.apps.gold.devops.gov.bc.ca/track', 'created_date': datetime.utcnow(), 'created_by': 'system', 'is_active': True},
            {'app_name': 'EPIC Track', 'environment': 'PROD', 'url': 'https://system.eao.gov.bc.ca/track', 'created_date': datetime.utcnow(), 'created_by': 'system', 'is_active': True},

            # COMPLIANCE
            {'app_name': 'EPIC Compliance', 'environment': 'DEV', 'url': 'https://eao-dev.apps.gold.devops.gov.bc.ca/compliance', 'created_date': datetime.utcnow(), 'created_by': 'system', 'is_active': True},
            {'app_name': 'EPIC Compliance', 'environment': 'TEST', 'url': 'https://eao-test.apps.gold.devops.gov.bc.ca/compliance', 'created_date': datetime.utcnow(), 'created_by': 'system', 'is_active': True},
            {'app_name': 'EPIC Compliance', 'environment': 'PROD', 'url': 'https://system.eao.gov.bc.ca/compliance', 'created_date': datetime.utcnow(), 'created_by': 'system', 'is_active': True},

            # ENGAGE
            {'app_name': 'EPIC Engage', 'environment': 'DEV', 'url': 'https://dev.engage.eao.gov.bc.ca', 'created_date': datetime.utcnow(), 'created_by': 'system', 'is_active': True},
            {'app_name': 'EPIC Engage', 'environment': 'TEST', 'url': 'https://test.engage.eao.gov.bc.ca', 'created_date': datetime.utcnow(), 'created_by': 'system', 'is_active': True},
            {'app_name': 'EPIC Engage', 'environment': 'PROD', 'url': 'https://engage.eao.gov.bc.ca', 'created_date': datetime.utcnow(), 'created_by': 'system', 'is_active': True},

             # CONDITION REPO
            {'app_name': 'Condition Repository', 'environment': 'DEV', 'url': 'https://eao-dev.apps.gold.devops.gov.bc.ca/condition', 'created_date': datetime.utcnow(), 'created_by': 'system', 'is_active': True},
            {'app_name': 'Condition Repository', 'environment': 'TEST', 'url': 'https://eao-test.apps.gold.devops.gov.bc.ca/condition', 'created_date': datetime.utcnow(), 'created_by': 'system', 'is_active': True},
            {'app_name': 'Condition Repository', 'environment': 'PROD', 'url': 'https://system.eao.gov.bc.ca/condition', 'created_date': datetime.utcnow(), 'created_by': 'system', 'is_active': True},

            # EAGLE ADMIN
            {'app_name': 'Eagle Admin (EPIC)', 'environment': 'DEV', 'url': 'https://epic-dev.apps.silver.devops.gov.bc.ca', 'created_date': datetime.utcnow(), 'created_by': 'system', 'is_active': True},
            {'app_name': 'Eagle Admin (EPIC)', 'environment': 'TEST', 'url': 'https://epic-test.apps.silver.devops.gov.bc.ca', 'created_date': datetime.utcnow(), 'created_by': 'system', 'is_active': True},
            {'app_name': 'Eagle Admin (EPIC)', 'environment': 'PROD', 'url': 'https://projects.eao.gov.bc.ca', 'created_date': datetime.utcnow(), 'created_by': 'system', 'is_active': True},
        ]
    )

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('application_urls')
    # ### end Alembic commands ###
